# Generated by Django 6.0.4 on 2026-04-18 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='confirmada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consulta',
            name='lembrete_enviado',
            field=models.BooleanField(default=False),
        ),
    ]
