# Generated by Django 6.0.4 on 2026-04-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_bot', '0002_consulta_confirmada_consulta_lembrete_enviado'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='convenio',
            field=models.CharField(blank=True, default='Particular', max_length=100, null=True),
        ),
    ]
